mqtt_server: # mqtt server config
  host: # your MQTT Broker Server IP, default is your PC's LAN IP
  port:  # your MQTT Broker Server Port, default is 1883
  keep_alive: ## max alive of mqtt topic connect session
  topic_connect: # connect to robot topic
  topic_control: # control robot topic
robot:
  grab_distance: # the maximum distance before starting the grab autonomously