detection:
  image_url: # the full path to the MJPEG stream
  failed_detection_threshold: # the number of failed detections before the robot switches to roaming again
  bottom_blackout_height: # the number of pixels from the bottom to ignore (if robot is in view)
  start_pickup_vdist: # the number of pixels from the bottom after which the robot should start the pickup procedure (is added to bottom_blackup_height)

mqtt_server: # mqtt server config
  host: # your MQTT Broker Server IP, default is your PC's LAN IP
  port: # your MQTT Broker Server Port, default is 1883
  keep_alive: 60 ## max alive of mqtt topic connect session
  topic: topic/control # control robot topic
